# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 9081
    onOpen: ignore
    visibility: public
  - port: 8000
    onOpen: open-browser

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      yarn install &&
      source ./scripts/set_cms_proxy.sh &&
      ./scripts/set_env_vars.sh
  - command: |
      yarn cms-proxy
  - command: |
      yarn develop
